---
title: "Guided Exercise 02"
author: "Zev Rosen"
date: "9/23/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load}
##load in library and required datasets
library(tidyverse)
player_data <- read.csv("Master.csv")
pitching_data <- read.csv("Pitching.csv")
salary_data <- read.csv("Salaries.csv")
inflation_index <- read.csv("inflation.csv")

```
```{r 1}
#side by side boxplots
pitching_data$yearID <- as.factor(pitching_data$yearID)
ggplot(pitching_data) + geom_boxplot(aes(x=yearID, y= ERA))

```

```{r 2}
#line graph of median
summary_ERA <- summarize(group_by(pitching_data, yearID), Q1 = quantile(ERA, .25, na.rm =T), median = median(ERA, na.rm = T), Q3 = quantile(ERA,.75, na.rm = T), min = min(ERA, na.rm = T), max = max(ERA, na.rm = T))
summary_ERA$yearID <- as.numeric(as.character(summary_ERA$yearID))
ggplot(summary_ERA) + geom_line(aes(x=yearID, y = median))

```

```{r 3}
#quartile/ribbon graph
ggplot(summary_ERA) +
  geom_ribbon(aes(x = yearID, ymin = Q1, ymax = Q3), fill = "lightgreen")+
  geom_line(aes(x = yearID, y = median), color = "darkblue") 
```
```{r 4}
#filter pitching data into players who have pitched at least 10 games
pitching_data <- pitching_data[pitching_data$G >= 10,]
##convert ERA to numeric vaule
pitching_data$ERA <- as.numeric(pitching_data$ERA)
#Convert year to numeric values
pitching_data$yearID <- as.numeric(as.character(pitching_data$yearID))
##compute summary statistics
summary_ERA_2 <- summarize(group_by(pitching_data, yearID), median = median(ERA, na.rm = T), count = n(), unique_count = n_distinct(playerID), threeminus_ERAS = sum(ERA <= 3), sixplus_ERAS = sum(ERA >= 6),
threeminus_ERAS_proportion = mean(ERA <=3),
sixplus_ERAS_proportion = mean(ERA >= 6),
total_ERA = sum(ERA), top_ERA = max(ERA), bottom_ERA = min(ERA))

#plot of proportion of pitchers (with at least 10 games) with low and high ERAS each year
ggplot(summary_ERA_2) + 
  geom_line(aes(x = yearID, y = threeminus_ERAS_proportion, color = "3 or under"))+
  geom_line(aes(x = yearID, y = sixplus_ERAS_proportion, color = "6 or higher"))+
  scale_color_manual(values = c("6 or higher" = "red", "3 or under" = "darkblue"), 
    name = "ERA",
    labels = c("3 or under", "6 or higher "))+#end scale color manual
  scale_x_continuous(name = "Year")+
  scale_y_continuous(name = "Proportion")+
  labs(title ="Proportion of Pitchers (pitching at least 10 games) \n With Low and High ERAs by Year")
```


```{r 5}
#creating a primary key using a mutate command
salary_data_keyed <- mutate(salary_data, row_num = row_number())
#makes the key for inflation index match that in salary data
names(inflation_index)[1] <- "yearID" 

player_data$playerID <- as.character(player_data$playerID)
salary_data$playerID <- as.character(salary_data$playerID)
summary_player_salary <- left_join(player_data, salary_data, by = "playerID")
summary_player_salary$usborn <- ifelse(summary_player_salary$birthCountry == "USA", "Born in USA", "Born Outside USA" )
summary_player_salary2 <- summarize(group_by(summary_player_salary, yearID, usborn), Q1 = quantile(salary, .25, na.rm =T), median = median(salary,na.rm = T), Q3 = quantile(salary,.75, na.rm = T))
#remove NA values from last two lines 
summary_player_salary2 <- summary_player_salary2[-c(63,64),]
#add 2015 to inflation index
inflation_index <- rbind(inflation_index, c(2015,1.00))
#make summary data
summary_player_salary2 <- left_join(summary_player_salary2, inflation_index, by = "yearID")
#adjust for inflation
summary_player_salary3 <- mutate(summary_player_salary2, median_inflation_adjusted = median*inflation2015, Q1_inflation_adjusted = Q1*inflation2015, Q3_inflation_adjusted = Q3*inflation2015)
#make graph showing salaries of middle 50% of earners
ggplot(summary_player_salary3)+geom_ribbon(aes(x=yearID, ymin=Q1_inflation_adjusted, ymax=Q3_inflation_adjusted, fill=as.factor(usborn)), alpha = 0.4)+geom_line(aes(x=yearID, y=median_inflation_adjusted, color = usborn))+scale_y_continuous(labels = scales::dollar)+labs(y="Annual Salary  \n (Adjusted for Inflation)",x="Year",title="Salaries of Middle 50% of Earners in Major League Baseball")+theme_classic()+scale_color_hue("Median Salary")+scale_fill_discrete(name = "Middle 50% of Earners")
```



