---
title: "Guided Exercise 03"
author: "Zev Rosen"
date: "10/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
The first graph shows the proportion of house representatives who are women in each state. 
```{r graph1}
library(tidyverse)
all_states <- map_data("state")
congress <- read_csv("womenincongress.csv")
names(congress)[2] <- "region"
stateData <- left_join(all_states, congress, by = "region" )
##add repprop variable 
stateData <- mutate(stateData,repprop = representatives/total)
##make plot 
housePlot <- ggplot() + geom_polygon(data = stateData, aes(x= long, y = lat, group = group, fill = repprop), color = "grey50") + coord_map() + labs(x = "", y = "", title = "Women in the House") + theme_classic() + theme(axis.ticks.y = element_blank(), axis.text.y = element_blank(), axis.ticks.x = element_blank(), axis.text.x = element_blank())
housePlot <- housePlot + scale_fill_gradient(name = "Female Representatives", low = "whitesmoke", high = "darkred")
housePlot
```

The second plot shows the results of the 2012 election in the South. 

```{r graph2}
##load in data 
electionData <- read_csv("2012.csv")
names(electionData)[1] <- "region"
electionData$ObamaPerc <- electionData$ObamaVotes/(electionData$ObamaVotes+electionData$RomneyVotes+electionData$JohnsonVotes+electionData$SteinVotes)
electionData$RomneyPerc <- electionData$RomneyVotes/(electionData$ObamaVotes+electionData$RomneyVotes+electionData$JohnsonVotes+electionData$SteinVotes)
electionData <- merge(all_states,electionData,by="region")
#make plot 
south <- filter(electionData, region %in% c("delaware", "florida", "georgia", "maryland", "north carolina", "south carolina", "virginia", "district of columbia", "west virginia", "alabama", "kentucky", "mississippi", "tennessee", "arkansas", "louisiana", "oklahoma", "texas"))
southelectionPlot <-
ggplot()+geom_polygon(data=south,aes(x=long, y=lat, group = group, fill=ObamaPerc),color="grey50")+coord_map()+labs(x="",y="",title="2012 Election Results")+theme_classic()+ theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(), axis.ticks.x = element_blank(),axis.text.x = element_blank()) + scale_fill_gradient2(name="Obama's Percentage",low="red",mid="white",high="blue",midpoint=.5)
southelectionPlot
```

